### ISSUE TITLE
Is this upgrade for Kernel 4.8 based on fliusb-1.3  or  fliusb-1.3.2 ?

### ISSUE THREAD

**Issue by ppmim** [SydneyAstrophotonicInstrumentationLab/FLI-linux#1]
On the FLI web site they have the  fliusb-1.3.2, and it includes some conditional compilation for Kernel 4.6.

**Comment by ppmim** [comment]
I have just tried to compile this version (for Ubuntu 16.04 LTS with 4.8.0-39-generic) on a Debian 9 with kernel 4.9.x (Linux arch 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux) and it gives a compilation **error** regarding 'get_user_pages_remote' call.

However, fliusb-1.3.2 version compiles without problems on Debian9.

**Comment by christhechris** [comment]
Hi ppmim, thanks for sharing, good to see they updated. This was based on 1.3, not 1.3.2 (appears to be realised since I last looked). The official version is probably the best recommendation for new stuff.
